### ISSUE TITLE
Relic Deployment Notification

### ISSUE THREAD

**Issue by AtifAhmed** [newrelic/newrelic_api#16]
Hi,

I wanted to know if its possible to post data to https://api.newrelic.com/deployments.xml using an Ajax call from a .net Page to log Deployment info in Relic. 

Basically my requirement is to log deployment details with some custom data to relic on a button click from a.net page. Please advise the best way to post data. Thanks

**Comment by tkrajcar** [comment]
Hi @AtifAhmed,

You should POST to https://api.newrelic.com/deployments.xml with the `deployment[description]` and `deployment[app_name]` as parameters, and `x-api-key` set as an HTTP header. See our docs page for more information: https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/setting-deployment-notifications

Since we require the New Relic API key to be sent on every deployment notification, you may want to create a page in your .NET app that is responsible for sending this POST, and trigger that from your page, so you don't have to disclose the API key to users.
